[
  {
    name: `21.5" iMac`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Dual Core I5" 1.4Ghz`,
    ram: "8GB Ram",
    memory: "500GB HDD",
    year: "Mid-2014",
    price: "£450",
  },
  {
    name: `21.5" iMac`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core I5" 2.7Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: "(Late 2012/13)",
    price: "£500",
  },
  {
    name: `21.5" iMac`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core I5" 3.0Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(4K, Mid-2017) (USB-C Thunderbolt 3)`,
    price: "£849",
  },
  {
    name: `21.5" iMac`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core I5" 3.1Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(4K, Late 2015)`,
    price: "£750",
  },
  {
    name: `21.5" iMac`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core I7" 3.1Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012/13)`,
    price: "£650",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core 2 Duo" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2009)`,
    price: "£275",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i3" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2010)`,
    price: "£300",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i5" 2.5Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2011)`,
    price: "£325",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i7" 2.8Ghz`,
    ram: "4GB Ram",
    memory: "1TB HDD",
    year: `(Mid-2011)`,
    price: "£375",
  },
  {
    name: `27" iMac (slim)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i5" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012/13)`,
    price: "£700",
  },
  {
    name: `27" iMac (slim)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i5" 3.2Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2013)`,
    price: "£750",
  },
  {
    name: `27" iMac (slim)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i5" 3.4Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2013)`,
    price: "£800",
  },
  {
    name: `27" iMac (slim)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core i7" 3.5Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012)`,
    price: "£850",
  },
  {
    name: `27" iMac Aluminium`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Quad Core Duo" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "1TB HDD",
    year: `(Late 2009)`,
    price: "No price currently available",
  },
  {
    name: `27" iMac Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `”14 Core" 2.5Ghz Xeon W`,
    ram: "64GB Ram",
    memory: "1TB SSD",
    year: `(Late 2017)`,
    price: "£5499",
  },
  {
    name: `27" iMac Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `”10 Core" 3.0Ghz Xeon W`,
    ram: "32GB Ram",
    memory: "1TB SSD",
    year: `(Late 2017)`,
    price: "£4799",
  },
  {
    name: `27" iMac Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `”8 Core" 3.2Ghz Xeon W`,
    ram: "32GB Ram",
    memory: "1TB SSD",
    year: `(Late 2017)`,
    price: "£3299",
  },
  {
    name: `Apple Mac Mini`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.3Ghz `,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2011)`,
    price: "£300",
  },
  {
    name: `Apple Mac Mini`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.5Ghz `,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2012)`,
    price: "£350",
  },
  {
    name: `Apple Mac Mini`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.6Ghz `,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2014)`,
    price: "£450",
  },
  {
    name: `Apple Mac Mini`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 3.0Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2018)`,
    price: "£899",
  },
  {
    name: `Apple Mac Mini`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7” 3.2Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Late 2018)`,
    price: "£999",
  },
  {
    name: `Apple Mac Pro 6.1 "Trashcan"`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `Intel Based "Quad Core" Desktop 3.7Ghz`,
    ram: "12GB Ram",
    memory: "256GB SSD",
    year: `No year available`,
    price: "£1100",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core I5" 1.4Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2014)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.0Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2012)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2011)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 1.8Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2011)`,
    price: "No price available",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.8GHZ`,
    ram: "8GB Ram",
    memory: "128Gb SSD",
    year: `(2017)`,
    price: "£700",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.4GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2014)`,
    price: "£500",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2015)`,
    price: "£550",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.8GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2012)`,
    price: "£450",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.2GHZ`,
    ram: "8GB Ram",
    memory: "128Gb SSD",
    year: `(2017)`,
    price: "£750",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.0GHZ`,
    ram: "4GB Ram",
    memory: "256Gb SSD",
    year: `(Mid-2012)`,
    price: "£550",
  },
  {
    name: `13 inch Apple Macbook Air Retina Display Touch ID`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(2018)`,
    price: "£850",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core 2 Duo" 2.26Ghz`,
    ram: "2GB Ram",
    memory: "160GB HDD",
    year: `(Mid-2009)`,
    price: "£250",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core 2 Duo" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "250GB HDD",
    year: `(Mid-2010)`,
    price: "£275",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.3Ghz`,
    ram: "4GB Ram",
    memory: "320GB HDD",
    year: `(Early 2011)`,
    price: "£400",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2011)`,
    price: "£450",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.5Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid 2012)`,
    price: "£500",
  },
  {
    name: `13 inch Macbook Pro`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "750GB HDD",
    year: `(Mid 2012)`,
    price: "£550",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£900",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 3.3Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£1050",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar Touch ID`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.4Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2019)`,
    price: "£1000",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.0Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Late 2016)`,
    price: "£700",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 2.3Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Mid 2017)`,
    price: "£800",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.4Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£850",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.5Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Mid 2017)`,
    price: "£1000",
  },
];

// 15 inch Unibody
// Apple MacBook Pro "Core 2 Duo" 15 inch (Unibody) 2.4Ghz 4GB Ram 320GB HDD (Late 2008) £275
// Apple MacBook Pro "Core 2 Duo" 15inch (Unibody) 2.66Ghz 4GB Ram 320GB HDD (Mid-2009) £300
// Apple MacBook Pro "Quad Core i7" 15 inch (Unibody) 2.3Ghz 8GB Ram 500GB HDD (Mid-2012) £550
// Apple Macbook Pro “Quad Core I7" 2.0Ghz 8Gb 256Gb Ssd 15 inch Retina Display (Late 2013) £700
// Apple MacBook Pro “Quad Core i7" 2.3Ghz 8Gb 256GB SSD 15 inch Retina Display (Mid-2012) £650
// Apple MacBook Pro “Quad Core i7" 2.2Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2014) £950
// Apple MacBook Pro “Quad Core i7" 2.5Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2014) £1050
// Apple MacBook Pro “Quad Core i7" 2.8Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2014) £1150
// Apple MacBook Pro “Quad Core i7" 2.2Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2015) £1050
// Apple MacBook Pro “Quad Core i7" 2.5Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2015) £1150
// Apple MacBook Pro “Quad Core i7" 2.8Ghz 16Gb 256GB SSD 15 inch Retina Display (Mid 2015) £1250

// 15 inch Touch Bar
// 15 inch Retina Display (Touch Bar) Apple MacBook Pro "Quad Core i7" 2.6Ghz 16GB Ram 256GB SSD (Late 2016) £1200
// 15 inch Retina Display (Touch Bar) Apple MacBook Pro "Quad Core I7" 2.8Ghz 16GB Ram 256GB SSD (Mid 2017) £1400
// 15 inch Retina Display (Touch Bar) Apple MacBook Pro "Quad Core i7" 2.9Ghz 16GB Ram 256GB SSD (Late 2016) £1300
// 15inch Retina Display (Touch Bar) Apple Macbook Pro “6 Core I7" 2.2Ghz 16Gb Ram 256Gb SSD (Mid 2018) £1700

// 16 inch Touch Bar
// 16 inch Retina Display (Touch Bar) Apple Macbook Pro “6 Core I7" 2.6Ghz 16Gb Ram 512Gb SSD (Mid 2019) £1800
// 16 inch Retina Display (Touch Bar) Apple Macbook Pro “8 Core I9” 2.3Ghz 16Gb Ram 1TB SSD (2020) £2400

// 17 inch Macbook Pro
// 17 Inch Unibody Apple Macbook Pro "Core I5" 2.53Ghz 4GB Ram 500GB HDD (Mid 2010) £450
// 17 Inch Unibody Apple MacBook Pro "Quad Core i7" 2.2Ghz 4GB Ram 750GB HDD (Early 2011) £550
// 17 Inch Unibody Apple MacBook Pro "Quad Core i7" 2.4Ghz 4GB Ram 750GB HDD (Late 2011) £650
// 17 Inch Unibody Apple MacBook Pro "Core 2 Duo" 2.66Ghz 4GB Ram 500GB HDD (Early 2009) £350
// 17 Inch Unibody Apple Macbook Pro "Core 2 Duo" 3.06Ghz 4GB Ram 500GB Hdd (Mid-2009) £400
