// const productsForSale = [
//   {
//     name: `21.5" iMac`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Dual Core I5" 1.4Ghz`,
//     ram: "8GB Ram",
//     memory: "500GB HDD",
//     year: "Mid-2014",
//     price: "£450",
//   },
//   {
//     name: `21.5" iMac`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core I5" 2.7Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: "(Late 2012/13)",
//     price: "£500",
//   },
//   {
//     name: `21.5" iMac`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core I5" 3.0Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(4K, Mid-2017) (USB-C Thunderbolt 3)`,
//     price: "£849",
//   },
//   {
//     name: `21.5" iMac`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core I5" 3.1Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(4K, Late 2015)`,
//     price: "£750",
//   },
//   {
//     name: `21.5" iMac`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core I7" 3.1Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2012/13)`,
//     price: "£650",
//   },
//   {
//     name: `21.5" iMac Aluminium`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 3.06Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Late 2009)`,
//     price: "£275",
//   },
//   {
//     name: `21.5" iMac Aluminium`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i3" 3.06Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid-2010)`,
//     price: "£300",
//   },
//   {
//     name: `21.5" iMac Aluminium`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i5" 2.5Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid-2011)`,
//     price: "£325",
//   },
//   {
//     name: `21.5" iMac Aluminium`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.8Ghz`,
//     ram: "4GB Ram",
//     memory: "1TB HDD",
//     year: `(Mid-2011)`,
//     price: "£375",
//   },
//   {
//     name: `27" iMac (slim)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i5" 2.9Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2012/13)`,
//     price: "£700",
//   },
//   {
//     name: `27" iMac (slim)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i5" 3.2Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2013)`,
//     price: "£750",
//   },
//   {
//     name: `27" iMac (slim)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i5" 3.4Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2013)`,
//     price: "£800",
//   },
//   {
//     name: `27" iMac (slim)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 3.5Ghz`,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2012)`,
//     price: "£850",
//   },
//   {
//     name: `27" iMac Aluminium`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core Duo" 3.06Ghz`,
//     ram: "4GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2009)`,
//     price: "No price currently available",
//   },
//   {
//     name: `27" iMac Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `”14 Core" 2.5Ghz Xeon W`,
//     ram: "64GB Ram",
//     memory: "1TB SSD",
//     year: `(Late 2017)`,
//     price: "£5499",
//   },
//   {
//     name: `27" iMac Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `”10 Core" 3.0Ghz Xeon W`,
//     ram: "32GB Ram",
//     memory: "1TB SSD",
//     year: `(Late 2017)`,
//     price: "£4799",
//   },
//   {
//     name: `27" iMac Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `”8 Core" 3.2Ghz Xeon W`,
//     ram: "32GB Ram",
//     memory: "1TB SSD",
//     year: `(Late 2017)`,
//     price: "£3299",
//   },
//   {
//     name: `Apple Mac Mini`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.3Ghz `,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid-2011)`,
//     price: "£300",
//   },
//   {
//     name: `Apple Mac Mini`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.5Ghz `,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Late 2012)`,
//     price: "£350",
//   },
//   {
//     name: `Apple Mac Mini`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.6Ghz `,
//     ram: "8GB Ram",
//     memory: "1TB HDD",
//     year: `(Late 2014)`,
//     price: "£450",
//   },
//   {
//     name: `Apple Mac Mini`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 3.0Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2018)`,
//     price: "£899",
//   },
//   {
//     name: `Apple Mac Mini`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7” 3.2Ghz`,
//     ram: "8GB Ram",
//     memory: "128GB SSD",
//     year: `(Late 2018)`,
//     price: "£999",
//   },
//   {
//     name: `Apple Mac Pro 6.1 "Trashcan"`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `Intel Based "Quad Core" Desktop 3.7Ghz`,
//     ram: "12GB Ram",
//     memory: "256GB SSD",
//     year: `No year available`,
//     price: "£1100",
//   },
//   {
//     name: `11.6" Apple Macbook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core I5" 1.4Ghz`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Early 2014)`,
//     price: "No price available",
//   },
//   {
//     name: `11.6" Apple Macbook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.0Ghz`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Mid-2012)`,
//     price: "No price available",
//   },
//   {
//     name: `11.6" Apple Macbook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.6Ghz`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Mid-2011)`,
//     price: "No price available",
//   },
//   {
//     name: `11.6" Apple Macbook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 1.8Ghz`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Mid-2011)`,
//     price: "No price available",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.8GHZ`,
//     ram: "8GB Ram",
//     memory: "128Gb SSD",
//     year: `(2017)`,
//     price: "£700",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.4GHZ`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Early 2014)`,
//     price: "£500",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.6GHZ`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Early 2015)`,
//     price: "£550",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.8GHZ`,
//     ram: "4GB Ram",
//     memory: "128Gb SSD",
//     year: `(Mid-2012)`,
//     price: "£450",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.2GHZ`,
//     ram: "8GB Ram",
//     memory: "128Gb SSD",
//     year: `(2017)`,
//     price: "£750",
//   },
//   {
//     name: `13 inch Apple MacBook Air`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.0GHZ`,
//     ram: "4GB Ram",
//     memory: "256Gb SSD",
//     year: `(Mid-2012)`,
//     price: "£550",
//   },
//   {
//     name: `13 inch Apple Macbook Air Retina Display Touch ID`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.6Ghz`,
//     ram: "8GB Ram",
//     memory: "128GB SSD",
//     year: `(2018)`,
//     price: "£850",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.26Ghz`,
//     ram: "2GB Ram",
//     memory: "160GB HDD",
//     year: `(Mid-2009)`,
//     price: "£250",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.4Ghz`,
//     ram: "4GB Ram",
//     memory: "250GB HDD",
//     year: `(Mid-2010)`,
//     price: "£275",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.3Ghz`,
//     ram: "4GB Ram",
//     memory: "320GB HDD",
//     year: `(Early 2011)`,
//     price: "£400",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.4Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Late 2011)`,
//     price: "£450",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.5Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid 2012)`,
//     price: "£500",
//   },
//   {
//     name: `13 inch Macbook Pro`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.9Ghz`,
//     ram: "8GB Ram",
//     memory: "750GB HDD",
//     year: `(Mid 2012)`,
//     price: "£550",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.9Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2016)`,
//     price: "£900",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 3.3Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2016)`,
//     price: "£1050",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display Touch Bar Touch ID`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 1.4Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2019)`,
//     price: "£1000",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.0Ghz`,
//     ram: "8GB Ram",
//     memory: "128GB SSD",
//     year: `(Late 2016)`,
//     price: "£700",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.3Ghz`,
//     ram: "8GB Ram",
//     memory: "128GB SSD",
//     year: `(Mid 2017)`,
//     price: "£800",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.4Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2016)`,
//     price: "£850",
//   },
//   {
//     name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i7" 2.5Ghz`,
//     ram: "8GB Ram",
//     memory: "128GB SSD",
//     year: `(Mid 2017)`,
//     price: "£1000",
//   },
//   {
//     name: `15" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.4Ghz`,
//     ram: "4GB Ram",
//     memory: "320GB HDD",
//     year: `(Late 2008)`,
//     price: "£275",
//   },
//   {
//     name: `15" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.4Ghz`,
//     ram: "4GB Ram",
//     memory: "320GB HDD",
//     year: `(Late 2008)`,
//     price: "£275",
//   },
//   {
//     name: `15" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.66Ghz`,
//     ram: "4GB Ram",
//     memory: "320GB HDD",
//     year: `(Mid-2009)`,
//     price: "£300",
//   },
//   {
//     name: `15" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.3Ghz`,
//     ram: "8GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid 2012)`,
//     price: "£550",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.0Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2013)`,
//     price: "£700",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.3Ghz`,
//     ram: "8GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2013)`,
//     price: "£650",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.2Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2014)`,
//     price: "£950",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.5Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2014)`,
//     price: "£1050",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.8Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2014)`,
//     price: "£1150",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.2Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2015)`,
//     price: "£1050",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.5Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2015)`,
//     price: "£1150",
//   },
//   {
//     name: `15" Macbook Pro (Unibody) Retina Display`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.8Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2015)`,
//     price: "£1250",
//   },
//   {
//     name: `15" Macbook Pro Retina Display touch bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.6Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2016)`,
//     price: "£1200",
//   },
//   {
//     name: `15" Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.8Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2017)`,
//     price: "£1400",
//   },
//   {
//     name: `15" Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.9Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Late 2016)`,
//     price: "£1300",
//   },
//   {
//     name: `15" Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"6 Core i7" 2.2Ghz`,
//     ram: "16GB Ram",
//     memory: "256GB SSD",
//     year: `(Mid 2018)`,
//     price: "£1700",
//   },
//   {
//     name: `16" Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"6 Core i7" 2.6Ghz`,
//     ram: "16GB Ram",
//     memory: "512GB SSD",
//     year: `(Mid 2019)`,
//     price: "£1800",
//   },
//   {
//     name: `16" Macbook Pro Retina Display Touch Bar`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"8 Core i9" 2.3Ghz`,
//     ram: "16GB Ram",
//     memory: "1TB SSD",
//     year: `(2020)`,
//     price: "£2400",
//   },
//   {
//     name: `17" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core i5" 2.53Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid 2010)`,
//     price: "£450",
//   },
//   {
//     name: `17" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.2Ghz`,
//     ram: "4GB Ram",
//     memory: "750GB HDD",
//     year: `(Early 2011)`,
//     price: "£550",
//   },
//   {
//     name: `17" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Quad Core i7" 2.4Ghz`,
//     ram: "4GB Ram",
//     memory: "750GB HDD",
//     year: `(Late 2011)`,
//     price: "£650",
//   },
//   {
//     name: `17" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 2.66Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Early 2009)`,
//     price: "£350",
//   },
//   {
//     name: `17" Macbook Pro (Unibody)`,
//     img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
//     processor: `"Core 2 Duo" 3.06Ghz`,
//     ram: "4GB Ram",
//     memory: "500GB HDD",
//     year: `(Mid 2009)`,
//     price: "£400",
//   },
// ];

// export default productsForSale;
