const iMacForSale = [
  {
    name: `21.5" iMac`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Dual Core I5" 1.4Ghz`,
    ram: "8GB Ram",
    memory: "500GB HDD",
    year: "Mid-2014",
    price: "£450",
  },
  {
    name: `21.5" iMac`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core I5" 2.7Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: "(Late 2012/13)",
    price: "£500",
  },
  {
    name: `21.5" iMac`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core I5" 3.0Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(4K, Mid-2017) (USB-C Thunderbolt 3)`,
    price: "£849",
  },
  {
    name: `21.5" iMac`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core I5" 3.1Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(4K, Late 2015)`,
    price: "£750",
  },
  {
    name: `21.5" iMac`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core I7" 3.1Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012/13)`,
    price: "£650",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2009)`,
    price: "£275",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i3" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2010)`,
    price: "£300",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i5" 2.5Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2011)`,
    price: "£325",
  },
  {
    name: `21.5" iMac Aluminium`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.8Ghz`,
    ram: "4GB Ram",
    memory: "1TB HDD",
    year: `(Mid-2011)`,
    price: "£375",
  },
  {
    name: `27" iMac (slim)`,
    img: "static/Macs/27inchSlimImac2012-2017.jpeg",
    processor: `"Quad Core i5" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012/13)`,
    price: "£700",
  },
  {
    name: `27" iMac (slim)`,
    img: "static/Macs/27inchSlimImac2012-2017.jpeg",
    processor: `"Quad Core i5" 3.2Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2013)`,
    price: "£750",
  },
  {
    name: `27" iMac (slim)`,
    img: "static/Macs/27inchSlimImac2012-2017.jpeg",
    processor: `"Quad Core i5" 3.4Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2013)`,
    price: "£800",
  },
  {
    name: `27" iMac (slim)`,
    img: "static/Macs/27inchSlimImac2012-2017.jpeg",
    processor: `"Quad Core i7" 3.5Ghz`,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2012)`,
    price: "£850",
  },
  {
    name: `27" iMac Aluminium`,
    img: "static/Macs/27inchImac.jpeg",
    processor: `"Quad Core Duo" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "1TB HDD",
    year: `(Late 2009)`,
    price: "No price currently available",
  },
];

export default iMacForSale;
