const MacBookAirfORsALE = [
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core I5" 1.4Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2014)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.0Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2012)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2011)`,
    price: "No price available",
  },
  {
    name: `11.6" Apple Macbook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 1.8Ghz`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2011)`,
    price: "No price available",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.8GHZ`,
    ram: "8GB Ram",
    memory: "128Gb SSD",
    year: `(2017)`,
    price: "£700",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.4GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2014)`,
    price: "£500",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Early 2015)`,
    price: "£550",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.8GHZ`,
    ram: "4GB Ram",
    memory: "128Gb SSD",
    year: `(Mid-2012)`,
    price: "£450",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.2GHZ`,
    ram: "8GB Ram",
    memory: "128Gb SSD",
    year: `(2017)`,
    price: "£750",
  },
  {
    name: `13 inch Apple MacBook Air`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i7" 2.0GHZ`,
    ram: "4GB Ram",
    memory: "256Gb SSD",
    year: `(Mid-2012)`,
    price: "£550",
  },
  {
    name: `13 inch Apple Macbook Air Retina Display Touch ID`,
    img: `process.env.PUBLIC_URL + "static/Macs/21.5inchimac.jpeg"`,
    processor: `"Core i5" 1.6Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(2018)`,
    price: "£850",
  },
];
