const macBookProForSale = [
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.26Ghz`,
    ram: "2GB Ram",
    memory: "160GB HDD",
    year: `(Mid-2009)`,
    price: "£250",
  },
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "250GB HDD",
    year: `(Mid-2010)`,
    price: "£275",
  },
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.3Ghz`,
    ram: "4GB Ram",
    memory: "320GB HDD",
    year: `(Early 2011)`,
    price: "£400",
  },
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2011)`,
    price: "£450",
  },
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.5Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid 2012)`,
    price: "£500",
  },
  {
    name: `13 inch Macbook Pro`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i7" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "750GB HDD",
    year: `(Mid 2012)`,
    price: "£550",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.9Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£900",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i7" 3.3Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£1050",
  },
  {
    name: `13 inch Macbook Pro Retina Display Touch Bar Touch ID`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 1.4Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2019)`,
    price: "£1000",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.0Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Late 2016)`,
    price: "£700",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.3Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Mid 2017)`,
    price: "£800",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i7" 2.4Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£850",
  },
  {
    name: `13 inch Macbook Pro Retina Display (Two Thunderbolt 3 Ports)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i7" 2.5Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Mid 2017)`,
    price: "£1000",
  },
  {
    name: `15" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "320GB HDD",
    year: `(Late 2008)`,
    price: "£275",
  },
  {
    name: `15" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "320GB HDD",
    year: `(Late 2008)`,
    price: "£275",
  },
  {
    name: `15" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.66Ghz`,
    ram: "4GB Ram",
    memory: "320GB HDD",
    year: `(Mid-2009)`,
    price: "£300",
  },
  {
    name: `15" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.3Ghz`,
    ram: "8GB Ram",
    memory: "500GB HDD",
    year: `(Mid 2012)`,
    price: "£550",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.0Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2013)`,
    price: "£700",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.3Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2013)`,
    price: "£650",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.2Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2014)`,
    price: "£950",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.5Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2014)`,
    price: "£1050",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.8Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2014)`,
    price: "£1150",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.2Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2015)`,
    price: "£1050",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.5Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2015)`,
    price: "£1150",
  },
  {
    name: `15" Macbook Pro (Unibody) Retina Display`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.8Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2015)`,
    price: "£1250",
  },
  {
    name: `15" Macbook Pro Retina Display touch bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.6Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£1200",
  },
  {
    name: `15" Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.8Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2017)`,
    price: "£1400",
  },
  {
    name: `15" Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.9Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Late 2016)`,
    price: "£1300",
  },
  {
    name: `15" Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"6 Core i7" 2.2Ghz`,
    ram: "16GB Ram",
    memory: "256GB SSD",
    year: `(Mid 2018)`,
    price: "£1700",
  },
  {
    name: `16" Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"6 Core i7" 2.6Ghz`,
    ram: "16GB Ram",
    memory: "512GB SSD",
    year: `(Mid 2019)`,
    price: "£1800",
  },
  {
    name: `16" Macbook Pro Retina Display Touch Bar`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"8 Core i9" 2.3Ghz`,
    ram: "16GB Ram",
    memory: "1TB SSD",
    year: `(2020)`,
    price: "£2400",
  },
  {
    name: `17" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core i5" 2.53Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid 2010)`,
    price: "£450",
  },
  {
    name: `17" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.2Ghz`,
    ram: "4GB Ram",
    memory: "750GB HDD",
    year: `(Early 2011)`,
    price: "£550",
  },
  {
    name: `17" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Quad Core i7" 2.4Ghz`,
    ram: "4GB Ram",
    memory: "750GB HDD",
    year: `(Late 2011)`,
    price: "£650",
  },
  {
    name: `17" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 2.66Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Early 2009)`,
    price: "£350",
  },
  {
    name: `17" Macbook Pro (Unibody)`,
    img: "static/Macs/21.5inchimac.jpeg",
    processor: `"Core 2 Duo" 3.06Ghz`,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid 2009)`,
    price: "£400",
  },
];

export default macBookProForSale;
