const otherForSale = [
  {
    name: `Apple Mac Mini`,
    img: "",
    processor: `"Core i5" 2.3Ghz `,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Mid-2011)`,
    price: "£300",
  },
  {
    name: `Apple Mac Mini`,
    img: "",
    processor: `"Core i5" 2.5Ghz `,
    ram: "4GB Ram",
    memory: "500GB HDD",
    year: `(Late 2012)`,
    price: "£350",
  },
  {
    name: `Apple Mac Mini`,
    img: "",
    processor: `"Core i5" 2.6Ghz `,
    ram: "8GB Ram",
    memory: "1TB HDD",
    year: `(Late 2014)`,
    price: "£450",
  },
  {
    name: `Apple Mac Mini`,
    img: "",
    processor: `"Core i5" 3.0Ghz`,
    ram: "8GB Ram",
    memory: "256GB SSD",
    year: `(Late 2018)`,
    price: "£899",
  },
  {
    name: `Apple Mac Mini`,
    img: "",
    processor: `"Core i7” 3.2Ghz`,
    ram: "8GB Ram",
    memory: "128GB SSD",
    year: `(Late 2018)`,
    price: "£999",
  },
  {
    name: `Apple Mac Pro 6.1 "Trashcan"`,
    img: "",
    processor: `Intel Based "Quad Core" Desktop 3.7Ghz`,
    ram: "12GB Ram",
    memory: "256GB SSD",
    year: `No year available`,
    price: "£1100",
  },
  {
    name: `Apple Mac Pro 6.1 "Trashcan"`,
    img: "",
    processor: `Intel Based "Quad Core" Desktop 3.7Ghz`,
    ram: "12GB Ram",
    memory: "256GB SSD",
    year: `No year available`,
    price: "£1100",
  },
];

export default otherForSale;
